### ISSUE TITLE
Python38 gyp-error

### ISSUE THREAD

**Issue by louischamaillard** [terrestris/mapfish-print-manager#320]
Hi ! 
very good-looking project.

I just can't install it as a node_module, due to 404 http errors on the version 4.10 of node-sass. Could you update it to version 5 released on October? Should work fine.
![image](https://user-images.githubusercontent.com/52458580/105728004-f2ff9280-5f2b-11eb-8064-37f636160b46.png)

**Comment by dnlkoch** [comment]
Hi @louischamaillard, thanks for your report! 

At least in its latest version the manager has no direct or transitive dependency to `node-sass`. Please try to install the latest version via `npm i --save @terrestris/mapfish-print-manager`.

Hope this helps!
