### ISSUE TITLE
Use typescript for type checking and creation of declaration files

### ISSUE THREAD

**Issue by simonseyock** [terrestris/mapfish-print-manager#336]
I looked into using tsc for typechecking the jsdoc annotations. This seems to work quite well as this project has jsdoc annotations on nearly every property and method. One thing that is a little difficult are the `clsSource` properties of the serializers and the `serializers` property of the manager.

I would suggest removing the `clsSource` property and instead add an abstract method `canSerialize` which accepts a source and returns a boolean. Apart from making this easier to type (and I think it is a more common way to do something like this), this would make this more flexible, you could for example only accepts wms layers that use a special host.

And instead of storing the classes in `serializers` we could store instances. I think this simplifies the process.

This would be a breaking change, but if there is interest in this I can create a PR when I find the time.

Adding `.d.ts` files after this should be fairly easy.

**Comment by simonseyock** [comment]
@dnlkoch @annarieger what do you think?

**Comment by dnlkoch** [comment]
I was thinking on migrating the manager to typescript at all several times. So yes, thanks for you proposal and I would be very interested in starting a discussion.

**Comment by simonseyock** [comment]
with typechecking the jsdoc annotations we would get most of the benefits of typescript without having to rewrite the whole project. It is more verbose, though. We could start with as little `strict` rules as possible and start enabling them one by one.
